### ISSUE TITLE
Received unexpected trace event (:gc_minor_start & :gc_minor_end)

### ISSUE THREAD

**Issue by qinfensky** [DockYard/flame_on#7] opened 2022-03-09 18:50 UTC
Elixir 1.13.3
Phoenix v1.6.6
{:flame_on, "~> 0.3.0"}

<img width="713" alt="image" src="https://user-images.githubusercontent.com/7803520/157510711-3a4f26da-c6ff-4400-bf39-d2198f9f8ca6.png">

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/7803520/157510614-9d66a27f-2317-43f5-b9f8-d636f32a6d6d.png">

<img width="1973" alt="image" src="https://user-images.githubusercontent.com/7803520/157510778-da3e702a-fd22-41c5-ba7c-7dd26f1c9fee.png">

(Output filename: flame_on_output_delete_me/1646851436679673-eflambe-output.bggg) I can't find this file

**Comment by TheFirstAvenger** [comment] 2022-03-09 19:04
[This has been resolved](https://github.com/Stratus3D/eflambe/pull/13) in the underlying library that we rely on, but a new version of that hasn't been cut since it was merged. I will push a new version of Flame On once they cut a new version.

**Comment by gaslit** [comment] 2022-03-17 13:12
> [This has been resolved](https://github.com/Stratus3D/eflambe/pull/13) in the underlying library that we rely on, but a new version of that hasn't been cut since it was merged. I will push a new version of Flame On once they cut a new version.

Hi I also have the same error. May I know if you have any advise on a workaround in the meantime like the necessary code changes if that is restricted to only the library? Many thanks.

**Comment by TheFirstAvenger** [comment] 2022-03-17 13:35
@gaslit are you having issues beyond the warnings in the logs? Is the flamegraph rendering? If not, is that output file present in your project? This ticket is in regards to `:gc_minor_start` and `:gc_minor_end` warnings which are red herrings and can be ignored. The `:return_to` messages I have also seen during normal runs. The `:unlink` one is new to me.

**Comment by gaslit** [comment] 2022-03-17 13:41
I have edited my post.

No other issues

2. Flamegraph does not render.

3. Output file does not exist: `Output filename: flame_on_output_delete_me/1647524175532330-eflambe-output.bggg` but i thought it is deleted after creation

Many thanks

**Comment by jaimeiniesta** [comment] 2022-03-23 09:59
I can confirm this, I get many " Received unexpected trace event" both in my M1 dev and in Heroku. Also, the flamegraph doesn't render in many occasions.

**Comment by TheFirstAvenger** [comment] 2022-03-28 18:23
Thank you everyone for your reports on the issue of flamegraphs not rendering. This ticket is being used to track the `:gc_*` warnings in the logs, and #9 is tracking the issue of flamegraphs not rendering (they are unrelated), so if you are having issues with flamegraphs not rendering, subscribe to #9 for updates (and check out #11 which should either resolve these issues directly or give us the tools to be able to diagnose them)

**Closed** 2022-04-05 18:23 UTC
