### ISSUE TITLE
CSP nonces not applied

### ISSUE THREAD

**Issue by woylie** [DockYard/flame_on#39] opened 2023-11-29 02:04 UTC
LiveDashboard has a [`:csp_nonce_assign_key` option ](https://hexdocs.pm/phoenix_live_dashboard/Phoenix.LiveDashboard.Router.html#live_dashboard/2-options), but it appears that flame_on doesn't apply it.

<img width="1028" alt="image" src="https://github.com/DockYard/flame_on/assets/13847569/180d50f9-31c9-41b2-aff5-1f2a6cdd23fe">

**Comment by TheFirstAvenger** [comment] 2024-06-10 13:28
@woylie I am unable to reproduce this locally. If this is still an issue for you, could you provide steps to reproduce, or an example repo?

**Comment by TheFirstAvenger** [comment] 2024-06-15 16:37
Closing for now, feel free to reply if you are still having this issue and can provide steps to reproduce or an example repo.

**Closed by TheFirstAvenger** 2024-06-15 16:37 UTC

**Comment by atcherry** [comment] 2025-11-07 14:15
Hello @TheFirstAvenger ! I've encountered this issue. This is probably in relation to the note that can be found at the bottom of [this section](https://hexdocs.pm/phoenix_live_dashboard/Phoenix.LiveDashboard.PageBuilder.html#module-custom-hooks) in the live_dashboard docs.  I see none of your `style` tags accept the `nonce` attribute. If you need more context, I'll try to get a reproducible repo for you.
